/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paquete;



/**
 *
 * @author Locky
 */
public class Vista_J_E1 extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista_J_E1() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botonmenu = new javax.swing.JButton();
        CuadroSuma = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CuadroPrimer = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        CuadroResta = new javax.swing.JTextField();
        CuadroDivision = new javax.swing.JTextField();
        CuadroMultiplicacion = new javax.swing.JTextField();
        CuadroSergundo = new javax.swing.JTextField();
        Boton_calcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Botonmenu.setText("Volver al menu");
        Botonmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonmenuActionPerformed(evt);
            }
        });
        getContentPane().add(Botonmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, -1, -1));

        CuadroSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuadroSumaActionPerformed(evt);
            }
        });
        getContentPane().add(CuadroSuma, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 110, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Segundo numero");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Resta");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        CuadroPrimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuadroPrimerActionPerformed(evt);
            }
        });
        getContentPane().add(CuadroPrimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Multiplicacion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Suma");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Division");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Primer numero");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        CuadroResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuadroRestaActionPerformed(evt);
            }
        });
        getContentPane().add(CuadroResta, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 110, -1));

        CuadroDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuadroDivisionActionPerformed(evt);
            }
        });
        getContentPane().add(CuadroDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 110, -1));

        CuadroMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuadroMultiplicacionActionPerformed(evt);
            }
        });
        getContentPane().add(CuadroMultiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 110, -1));

        CuadroSergundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CuadroSergundoActionPerformed(evt);
            }
        });
        getContentPane().add(CuadroSergundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 110, 30));

        Boton_calcular.setText("Calcular");
        Boton_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_calcularActionPerformed(evt);
            }
        });
        getContentPane().add(Boton_calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonmenuActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotonmenuActionPerformed

    private void CuadroSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuadroSumaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuadroSumaActionPerformed

    private void CuadroRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuadroRestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuadroRestaActionPerformed

    private void CuadroMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuadroMultiplicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuadroMultiplicacionActionPerformed

    private void CuadroDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuadroDivisionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuadroDivisionActionPerformed

    private void CuadroSergundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuadroSergundoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CuadroSergundoActionPerformed

    private void CuadroPrimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CuadroPrimerActionPerformed
     
    }//GEN-LAST:event_CuadroPrimerActionPerformed

    private void Boton_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_calcularActionPerformed
               Modelo_E1 mod = new Modelo_E1 ();
               
               int numero1, numero2 , resultadoS,resultadoR,resultadoM,resultadoD;
               numero1 = Integer.parseInt(CuadroPrimer.getText());
               numero2 = Integer.parseInt(CuadroSergundo.getText());

               mod.setNumero1(numero1);
               mod.setNumero2(numero2);

               mod.operaciones();


               CuadroSuma.setText(String.valueOf(mod.getSuma()));
               CuadroResta.setText(String.valueOf(mod.getResta()));
               CuadroMultiplicacion.setText(String.valueOf(mod.getProducto()));
               CuadroDivision.setText(String.valueOf(mod.getDivision()));
     
                       
        
    }//GEN-LAST:event_Boton_calcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_J_E1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_J_E1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_J_E1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_J_E1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
             //</editor-fold>
   }
    
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable(){        
                public void run() {
                new Vista_J_E1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Boton_calcular;
    public javax.swing.JButton Botonmenu;
    public javax.swing.JTextField CuadroDivision;
    public javax.swing.JTextField CuadroMultiplicacion;
    public javax.swing.JTextField CuadroPrimer;
    public javax.swing.JTextField CuadroResta;
    public javax.swing.JTextField CuadroSergundo;
    public javax.swing.JTextField CuadroSuma;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
