/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Final;


import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Equipo
 */
public class Usuario extends javax.swing.JFrame {

  public int buscar;
    public Usuario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Abonar = new javax.swing.JLabel();
        Retirar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        Saldo1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        monto1 = new javax.swing.JTextField();
        Saldo2 = new javax.swing.JTextField();
        monto2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CerrarSesion = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Actualizar = new javax.swing.JButton();
        nombre = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Abonar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Abonar.png"))); // NOI18N
        Abonar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Abonar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                AbonarMouseMoved(evt);
            }
        });
        Abonar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AbonarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AbonarMouseExited(evt);
            }
        });
        getContentPane().add(Abonar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, 60, -1));

        Retirar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Retirar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Retirar_1.png"))); // NOI18N
        Retirar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Retirar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                RetirarMouseMoved(evt);
            }
        });
        Retirar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RetirarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RetirarMouseExited(evt);
            }
        });
        getContentPane().add(Retirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        jSeparator1.setBackground(java.awt.Color.orange);
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 490, 20));

        jSeparator2.setBackground(java.awt.Color.orange);
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 720, 20));

        Saldo1.setEditable(false);
        Saldo1.setBackground(new java.awt.Color(255, 255, 255));
        Saldo1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Saldo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Saldo1ActionPerformed(evt);
            }
        });
        getContentPane().add(Saldo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 140, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Consultar Saldo ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        monto1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        monto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monto1ActionPerformed(evt);
            }
        });
        getContentPane().add(monto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 150, -1));

        Saldo2.setEditable(false);
        Saldo2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Saldo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Saldo2ActionPerformed(evt);
            }
        });
        getContentPane().add(Saldo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 160, -1));

        monto2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        monto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monto2ActionPerformed(evt);
            }
        });
        getContentPane().add(monto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 140, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Saldo    Total");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Monto a abonar ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, 30));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Retirar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 26)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Abonar");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 28)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Saldo Final");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, -1));

        CerrarSesion.setBackground(new java.awt.Color(255, 255, 255));
        CerrarSesion.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        CerrarSesion.setText("Cerrar Sesion");
        CerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(CerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Monto a Retirar");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        Actualizar.setBackground(new java.awt.Color(255, 255, 255));
        Actualizar.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 14)); // NOI18N
        Actualizar.setText("Actualizar Saldo");
        Actualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 85, 140, 40));

        nombre.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });
        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreKeyTyped(evt);
            }
        });
        getContentPane().add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 140, -1));

        jSeparator3.setBackground(java.awt.Color.orange);
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 30, 360));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono_dinero.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        jLabel12.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Usuario");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 20));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Azul2.jpeg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Saldo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Saldo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Saldo2ActionPerformed

    private void RetirarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RetirarMouseClicked
         try{
        
            // Se coge el valor que esta en el textField "Saldo1" y se obtiene el texto, despues se combierte a entero guardandose en "sald"
            String saldo = Saldo1.getText();
            int sald = Integer.parseInt(saldo);
            //Se coge el valor que hay en el textField "monto1" (el cual va a ser el valor que se desea retirar) y se combierte a entero
            int retiro = Integer.parseInt(monto1.getText());
            //con el siguiente if se plantea que si el saldo actual es mayor que el retiro, se descontara el monto a retirar del saldo total
            if(sald>=retiro && retiro>0 ){
            int total1 = sald - retiro;    
            String tot1 = Integer.toString(total1);
            //Se coloca el nuevo saldo en el textField "Saldo2"
            Saldo2.setText(tot1);
            //Coloca el cursor en el textField "monto1"
          
            monto1.requestFocus();
            //Selecciona todo lo que esta en  el textField "monto1"
            monto1.selectAll();
            
               
        }else{
                JOptionPane.showMessageDialog(null ,"Saldo insuficiente");//en caso de que no se cumpla la condicion inicial enviara esta notificacion 
             }
         }catch (Exception e){
           JOptionPane.showMessageDialog(null ,"Saldo insuficiente");//al no cumplir la excepcion se enviara esta notificacion al usuario 
       }
           
    }//GEN-LAST:event_RetirarMouseClicked

    private void AbonarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AbonarMouseClicked
        try{
            
            // Se coge el valor que esta en el textField "Saldo1" y se obtiene el texto, despues se combierte a entero guardandose en "sald"
            String saldo = Saldo1.getText();
            int sald = Integer.parseInt(saldo);
            //Se coge el valor que hay en el textField "monto1" (el cual va a ser el valor que se desea abonar) y se combierte a entero
            int abono = Integer.parseInt(monto2.getText()) ;
            
            //con el siguiente if se plantea que el manto a abonar tiene que ser mayor a 0 para poder hacer la transacción, donde dicho valor despues se sumará al saldo actual del usuario
            if(abono>0){
            int total2 = sald+abono;
            String tot2 = Integer.toString(total2);
            //Se coloca el nuevo saldo en el textField "Saldo2"
            Saldo2.setText(tot2);
            //Coloca el cursor en el textField "monto2"
            monto2.requestFocus();
            //Selecciona todo lo que esta een el textField "monto2"
            monto2.selectAll();
            
            }else{
                JOptionPane.showMessageDialog(null ,"abono invalido");//en caso de que no se cumpla la condicion inicial enviara esta notificacion 
                }
            
        }catch (Exception a) {
            JOptionPane.showMessageDialog(null ,"monto invalido");//al no cumplir la excepcion se enviara esta notificacion al usuario 
        
        }
        
    }//GEN-LAST:event_AbonarMouseClicked

    private void CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSesionActionPerformed
        Login pc = new Login();

        //en caso de que el usuario quiera salir del la sesion, se enviara esta notificacion para confirmar la accion
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Desea salir de la sesión", "Cerrar Sesión", dialog);

        if (result == 0) {
            pc.setVisible(true);
            this.dispose();
        }
        
        
    }//GEN-LAST:event_CerrarSesionActionPerformed

    private void monto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monto1ActionPerformed

    private void Saldo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Saldo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Saldo1ActionPerformed

    private void monto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monto2ActionPerformed

    private void RetirarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RetirarMouseMoved
        //Con el siguiente codigo se pone un borde blanco alrededor en la figura Retirar cuando se pone el mause ensima de este
        Retirar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250,250,250)));
    }//GEN-LAST:event_RetirarMouseMoved

    private void RetirarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RetirarMouseExited
        //Con el siguiente codigo se quita el borde de color blanco
        Retirar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(WIDTH, rootPaneCheckingEnabled)));
    }//GEN-LAST:event_RetirarMouseExited

    private void AbonarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AbonarMouseMoved
        //Con el siguiente codigo se pone un borde blanco alrededor en la figura Abonar cuando se pone el mause ensima de este
        Abonar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250,250,250)));
    }//GEN-LAST:event_AbonarMouseMoved

    private void AbonarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AbonarMouseExited
        //Con el siguiente codigo se quita el borde de color blanco
        Abonar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(WIDTH, rootPaneCheckingEnabled)));
    }//GEN-LAST:event_AbonarMouseExited

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        
        //Se obtiene el texto que esta en el textField "Saldo2" y se pone en Saldo1
        String Saldo = Saldo2.getText();
        Saldo1.setText(Saldo);

    }//GEN-LAST:event_ActualizarActionPerformed

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    private void nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyTyped
        //Cuando en el textField "nombre" se encuentre el nombre de alguno de los usuarios registrados en el textField "saldo1" se mostrará el saldo de dicho usuario
        int press = evt.getKeyChar();
        if (press == 10) {
            String Usuario_Igual = nombre.getText().trim();
            Clase_Usuario a;
            
            //Ya que la informacion de los usuarios esta guardada en el contenedor de "Admin" se convoca 
            for (int i = 0; i < Admin.contenedor.size(); i++) {
                a = (Clase_Usuario) Admin.contenedor.get(i);
                
                //Se obtiene el saldo que le pertenece al usuario y despues se inserta el texto en el textField "Saldo1"
                if (Usuario_Igual.equalsIgnoreCase(a.getUsuario())) {
                    
                    Saldo1.setText(a.getSaldo());
                    buscar = i;
                    break;
                }

            }
        }
    }//GEN-LAST:event_nombreKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Abonar;
    private javax.swing.JButton Actualizar;
    private javax.swing.JButton CerrarSesion;
    private javax.swing.JLabel Retirar;
    private javax.swing.JTextField Saldo1;
    public static javax.swing.JTextField Saldo2;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField monto1;
    private javax.swing.JTextField monto2;
    public static javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
